export const categories = [
  { index: "ability-scores", text: "Ability Scores" },
  { index: "alignments", text: "Alignments" },
  { index: "classes", text: "Classes" },
  { index: "conditions", text: "Conditions" },
  { index: "damage-types", text: "Damage Types" },
  { index: "equipment", text: "Equipment" },
  { index: "feats", text: "Feats" },
  { index: "features", text: "Features" },
  { index: "languages", text: "Languages" },
  { index: "magic-items", text: "Magic items" },
  { index: "magic-schools", text: "Magic Schools" },
  { index: "monsters", text: "Monsters" },
  { index: "proficiencies", text: "Proficiencies" },
  { index: "races", text: "Races" },
  { index: "rule-sections", text: "Rule Sections" },
  { index: "rules", text: "Rules" },
  { index: "skills", text: "Skills" },
  { index: "spells", text: "Spells" },
  { index: "subclasses", text: "Subclasses" },
  { index: "subraces", text: "Subraces" },
  { index: "traits", text: "Traits" },
  { index: "weapon-proficiencies", text: "Weapon Proficiencies" },
] as const;
